### ISSUE TITLE
Unable to detect widevine

### ISSUE THREAD

**Issue by popedagoat** [hyugogirubato/KeyDive#11]
what makes keydive unable to do so?

![Screenshot 2024-05-24 002534](https://github.com/hyugogirubato/KeyDive/assets/170604422/35c8da71-2df4-4cc1-8498-e9cdfaca7ac6)

**Comment by hyugogirubato** [comment]
Do you have Widevine on your emulator?

To check, install the application indicated in the [doc](https://github.com/hyugogirubato/KeyDive/blob/main/docs/PACKAGE.md#drm-info). You will then see if you have DRM on your emulator.

Please note that ROMs with DRM are only available with AVD Android Studio Play Store Rom edition which are not rooted by default.

**Comment by popedagoat** [comment]
wait, i read somewhere that only the Google APIs version and not the playstore version for the AVD that works. so i installed the Google API version and not the playstore one. but i also installed that DRM info app in the emulator it says that it does have Widevine L3.

so am i supposed to installed the playstore ROM version?

**Comment by hyugogirubato** [comment]
yes

**Comment by popedagoat** [comment]
now i've got a new problem after installing the Playstore version. and i stumbled upon the same problem on stackoverflow it says that i have to root the AVD?
![new problem](https://github.com/hyugogirubato/KeyDive/assets/170604422/ec0d247d-c7e6-4016-b125-418fe67e4ad4)

**Comment by hyugogirubato** [comment]
Read [docs](https://github.com/hyugogirubato/KeyDive/blob/main/docs%2FFUNCTIONS.md).
