### ISSUE TITLE
Cannot hook to the process even though all requirements are satisfied [Pixel 4a 5G]

### ISSUE THREAD

**Issue by azimabid00** [hyugogirubato/KeyDive#14]
![error_1](https://github.com/hyugogirubato/KeyDive/assets/110490898/172e77e9-80ca-4e81-b438-3e5a71204d3d)

![error_2](https://github.com/hyugogirubato/KeyDive/assets/110490898/f5364aec-a2e2-42c9-acfc-e963e92a1cb4)

![photo1717476247](https://github.com/hyugogirubato/KeyDive/assets/110490898/fcd208dc-eaff-48fa-97da-68cd2d6d2d27)

I have downgraded from L1 to L3 using oemcryptodisabler but somehow it still cannot hook to the process. It seems like it can't even find the process(?)

Also attached here is my function.xml file 
[function.zip](https://github.com/user-attachments/files/15542687/function.zip)

**Comment by hyugogirubato** [comment]
Sometimes there is a phenomenon where the DRM module is not initialized until it has been loaded the first time by a video player. This is also why the procedure indicates that you must first play a DRM video for the first time THEN launch the script and reload the page (bitmovie DRM demo player for example).

The page must remain active so that the module remains visible to Frida.

Try again following this order and keep me informed. (and yes, it is very likely that you will have to use function.xml given the topology of your device).

**Comment by azimabid00** [comment]
I tried with the method mentioned above, somehow it still cannot hook to the process.

But, I've made some progress after inspecting via logcat for the name of the process to be hooked :

![logcat](https://github.com/hyugogirubato/KeyDive/assets/110490898/d7b23e40-04fd-469b-905c-3c8d64f730f8)

so I tried to rename the targeted process name in vendor.py as such :

![hooks](https://github.com/hyugogirubato/KeyDive/assets/110490898/faacfa4c-4df2-49da-8e44-dac5842c0927)

which is a success, but weird because in DRM Info my SDK is 18.

And this brings me to another problem;

![error 3](https://github.com/hyugogirubato/KeyDive/assets/110490898/70e39b02-5eca-4b36-aada-498698d6b999)

**Comment by azimabid00** [comment]
Well I solved it thanks to the help of this comment: https://github.com/hyugogirubato/KeyDive/issues/13#issuecomment-2143741896 and it successfully hooked to the right process name.

![privkey](https://github.com/hyugogirubato/KeyDive/assets/110490898/3f759980-0aee-4dea-9290-affeeb062b46)

But I guess that Python has issues with my device name's whitespace which throws this error:

![error_dir](https://github.com/hyugogirubato/KeyDive/assets/110490898/ea480ef4-357a-45e7-929b-cf3a07fd72d3)

which I am too lazy to find out and fix, so I just modified the code in cdm.py line 252 to just make one level directory. https://github.com/hyugogirubato/KeyDive/blob/1e4d6ba88161bb99827d5576967ea651044020ce/extractor/cdm.py#L252

to

![path](https://github.com/hyugogirubato/KeyDive/assets/110490898/a6d8b6c1-5227-4ece-be89-5e5128b35c35)

All in all, much thanks to the author for this awesome code and for the support given.
