### ISSUE TITLE
 KeyDive: [WinError 2] El sistema no puede encontrar el archivo especificado

### ISSUE THREAD

**Issue by sesasa88** [hyugogirubato/KeyDive#16]
Good morning everyone, I am stuck here, how can I continue,Can somebody help me? thank you

![imagen](https://github.com/hyugogirubato/KeyDive/assets/172170092/7049d7b9-8a85-4a6a-a007-81e58a9b96fb)

**Comment by hyugogirubato** [comment]
The script does not detect ADB on your system, follow a tutorial on the internet (reboot required)

**Comment by sesasa88** [comment]
> The script does not detect ADB on your system, follow a tutorial on the internet (reboot required)

Thank you for your kind response, I didn't realize that could be the mistake. solved, have a good day
