### ISSUE TITLE
KeyDive timeout

### ISSUE THREAD

**Issue by Phantom03167** [hyugogirubato/KeyDive#17]
Hi everyone, I am stuck here. How can I continue. Can somebody help me? thank you! 
![图片](https://github.com/hyugogirubato/KeyDive/assets/79777907/515ecf05-badf-4067-b7e2-cb1eb3a759de)

**Comment by hyugogirubato** [comment]
The problem is in the hook of the `frida-server` binary which needs to be run as root. And if this is already the case, try deactivating/reducing SELinux (`setenforce 0`)
