### ISSUE TITLE
unable to access process with pid 

### ISSUE THREAD

**Issue by bybpow** [hyugogirubato/KeyDive#20]
I have my phone rooted with Magisk. I have Frida too. When I try this script I have the following error:
"2024-07-07 17:53:24 [E] Core: unable to access process with pid 719"

How can I solve this?

**Comment by hyugogirubato** [comment]
Frida is running as root on your device?

**NOTE**: To launch frida correctly, use MagiskFrida if you have magisk. If you use the binary directly, use the command as root user: `./frida-server -D` with 777 permissions on the binary

**Comment by bybpow** [comment]
Thanks. I was running Frida as instructed in their page with 755 but it seems 777 worked. Thanks for your help.

**Comment by hyugogirubato** [comment]
So you managed to get the script to work correctly?

**Comment by bybpow** [comment]
Yes. I already got my CDM. Again, thanks. I'm closing this.
