### ISSUE TITLE
Question | Extract keys from bin file

### ISSUE THREAD

**Issue by bybpow** [hyugogirubato/KeyDive#25]
I want to get my keys from the bin file to use it with mp4decrypt and ytdlp. Is this possible?

**Comment by hyugogirubato** [comment]
No it is not possible, a key is not present in the binary.

This is just used to bridge with an encrypted keybox file downloaded from the internet from Google.

You "necessarily* have to go through a dynamic interception to get a valid key.

**Comment by bybpow** [comment]
Thanks for the info.
