### ISSUE TITLE
Cannot dump CDM keys from WSA instance

### ISSUE THREAD

**Issue by sn-o-w** [hyugogirubato/KeyDive#27]
Hi, I installed Magisk Frida (the module) and I tried to dump CDM keys, but I get this:

<img src="https://github.com/user-attachments/assets/892fdf6e-d595-4543-9da7-4136c3cf11d0" width="250">
<img src="https://github.com/user-attachments/assets/733d6199-879e-425c-9b9e-37ffc28dd73b" width="500">

🤔

**Comment by hyugogirubato** [comment]
Mmm, the structure should be slightly different. Can you contact me via discord so that we can exchange and create a TeamViewer so that I can debug live?

**Comment by hyugogirubato** [comment]
Fixed in release 2.0.8: https://github.com/hyugogirubato/KeyDive/releases/tag/v2.0.8
