### ISSUE TITLE
(contact pls) not an issue

### ISSUE THREAD

**Issue by RevealedSoulEven** [hyugogirubato/KeyDive#30]
Can I please get your teleram or mail?

I need to collaborate to work on a project to fetch and mimic play integrity tokens
I did some research and figured out it is something we can achieve. I'm just lacking skills to continue that hooking part in gms like u did in liboemcrypto. I'll be waiting for your response.

Thank you

**Comment by hyugogirubato** [comment]
I have not specifically done any research regarding this protection system but I advise you to direct your research towards already existing modules such as `Universal SafetyNet Fix Version: 2.4.0`.

**Comment by RevealedSoulEven** [comment]
It's not regarding safetynet, it is something else, btw I managed to inject my own code into the app at runtime and generate my own token as many times I need, will soon work on it to help newbies.
