### ISSUE TITLE
Cant use keydive 

### ISSUE THREAD

**Issue by goicoecheamendy** [hyugogirubato/KeyDive#44]
hello, theres no keydive.py in new versions, im using windows and ubuntu
installed keydive using pip install keydive
and successfully installed
but when i trying to use the key dive got these errors :
Windows:
![image](https://github.com/user-attachments/assets/ab908142-8d32-4923-8f83-effa68ca0569)

Ubuntu:
![image](https://github.com/user-attachments/assets/4e05f0fd-454e-427f-b604-c4fcb3450b66)

please help me

**Comment by hyugogirubato** [comment]
python path issue

**Comment by goicoecheamendy** [comment]
can you please refer to any reference or solution  ?
