### ISSUE TITLE
Failed to disable L1 on Xiaomi mobile phone

### ISSUE THREAD

**Issue by yiz24** [hyugogirubato/KeyDive#5]
I have encountered a problem again, I'm a Xiaomi phone, the current software detection is L1, the use of the document provides a mask plug-in to disable L1, but the disable failed, The device is stuck on the startup screen, Fortunately, the brick saving plugin is installed, how to solve the problem?

**Comment by hyugogirubato** [comment]
@yiz24 
The problem you cite seems to be related to an incompatibility of oemcrypto disabler for your device. trying to contact the creators of this plugin directly but doesn't seem to be active for a while..
