### ISSUE TITLE
No data for device info, invalid argument position

### ISSUE THREAD

**Issue by Tontonnow** [hyugogirubato/KeyDive#7]
Android 12

It's on my phone.

31: (16, '16.0.1', 'android.hardware.drm@1.3-service.widevine', 'libwvhidl@1.3.so')

Newer versions don't work, older versions do

![image](https://github.com/hyugogirubato/KeyDive/assets/122251963/6f3b4a05-86e0-4af2-a20d-1930602d8150)
![image](https://github.com/hyugogirubato/KeyDive/assets/122251963/d0f1b455-8df8-4274-8945-953385d4f251)

**Comment by hyugogirubato** [comment]
@Tontonnow 

1. **Previous Working Version and Argument Position:**
   Can you tell me which previous version was working and/or the position of the argument indicated in the JavaScript script in accordance with your SDK?

2. **Warnings in the New Version:**
   Does the new version display any specific warnings, such as the use of a non-standard version of the vendor?
