### ISSUE TITLE
Failed to intercept the private key ANDROID 14

### ISSUE THREAD

**Issue by RevealedSoulEven** [hyugogirubato/KeyDive#8]
So basically when I provide the functions.xml then it gives this error
![image](https://github.com/hyugogirubato/KeyDive/assets/49313374/bd3b2cef-7216-4063-98e5-d664c21fbe31)

But when I remove that functions as stated in #2 then I get this
It is basically using the SDK 30 by default is that the issue? Or what?
![asdas](https://github.com/hyugogirubato/KeyDive/assets/49313374/93fc525b-c0ca-4429-b584-29d3d2c62611)
This error is 4 times coz everytime I tried to play video (in this case 4 times) it gave the same error

**Comment by RevealedSoulEven** [comment]
Ok so I used the magisk module to disable L1 widevine and its working now

**Comment by RevealedSoulEven** [comment]
Do you need the functions.xml ?
Or shall I send you the complete lib file

**Comment by RevealedSoulEven** [comment]
[function.zip](https://github.com/hyugogirubato/KeyDive/files/15367371/function.zip)
I'm attaching both files here

**Comment by hyugogirubato** [comment]
When I talk about the obfuscated name of the private function, I meant this:

![image](https://github.com/hyugogirubato/KeyDive/assets/65763543/d62e9195-9bc3-44bb-ad9d-bf8a9eff5fad)

This is the name associated with the address of the private function. This will complete the list of names known here:
https://github.com/hyugogirubato/KeyDive/blob/main/extractor/cdm.py#L22

Knowing the obfuscated name of the private function allows you to avoid hooking too many functions that could cause the script or library to crash.

**Comment by RevealedSoulEven** [comment]
Yes sir, Why not? Sure.

![image](https://github.com/hyugogirubato/KeyDive/assets/49313374/cf08606e-853c-4320-831e-21b17e607c00)

**Comment by RevealedSoulEven** [comment]
> Yes sir, Why not? Sure.
> 
> ![image](https://private-user-images.githubusercontent.com/49313374/331871757-cf08606e-853c-4320-831e-21b17e607c00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjIzMzksIm5iZiI6MTcxNjEyMjAzOSwicGF0aCI6Ii80OTMxMzM3NC8zMzE4NzE3NTctY2YwODYwNmUtODUzYy00MzIwLTgzMWUtMjFiMTdlNjA3YzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEyMzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMjQ1OGY0NjdhZjMzYzc5NTI4NTVjMWU2YjkzN2ZkMmVkOWI0ZTQzNThlNjcyMWYxMjZiNGZkMTU5OTEwN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bMKEEO9qzaSkdYofk5DP4OTDj3uuXppeyCtETDNfkQs)

I dont understand why it is showing too many functions at the end but anyways

**Comment by hyugogirubato** [comment]
Thanks for your feedback, I just added the function name in the code: https://github.com/hyugogirubato/KeyDive/commit/f18c34c8d036c112c88c540ba6930eb143c43378

If you use the code from the main branch with the latest commit, you should now only have three function hooks since the private function is already known.

**Comment by RevealedSoulEven** [comment]
![image](https://github.com/hyugogirubato/KeyDive/assets/49313374/bcd9d675-f70a-4c02-91ae-e6bfb50a48f5)

Still same even after using the latest commit but anyways I'm getting the output

**Comment by hyugogirubato** [comment]
I just checked and indeed I made a mistake on a letter, I made the correction here: https://github.com/hyugogirubato/KeyDive/commit/062d684e3ede2dd801023641d3a88f2a875d3078

This should work better now. The code is integrated into the new release
